linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused

linters-settings:
  gofmt:
    simplify: true

  misspell:
    locale: US

  goconst:
    min-len: 2
    min-occurrences: 2

  gosimple:
    checks: ["all"]

  staticcheck:
    checks: ["all"]

  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  revive:
    enable-all-rules: true
    rules:
      - name: line-length-limit
        arguments: [120]

  testifylint:
    enable-all: true

issues:
  exclude-dirs:
    - cmd/tools/goose-custom
    - docker
    - storage

run:
  timeout: 5m
