name: go-code-examples

services:
  go-app:
    container_name: go-app-container
    build:
      args:
        http_port: ${HTTP_PORT}
      context: .
      dockerfile: ./docker/dockerfile
    volumes:
      - ./storage/logs:/usr/app/storage/logs
    working_dir: /usr/app
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: ${DB_STRING}
    ports:
      - ${HTTP_PORT_PUBLIC}:${HTTP_PORT}
    depends_on:
      - db

  db:
    container_name: db-container
    image: postgres:17.0
    restart: always
    volumes:
      - ./storage/docker/.postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT_PUBLIC}:5432
