version: '3.7'
services:
  go-app:
    build:
      args:
        http_port: ${HTTP_PORT}
        debug_port: ${DELVE_DEBUG_PORT}
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./storage/logs:/usr/app/storage/logs
    working_dir: /usr/app
    environment:
      DELVE_DEBUG_PORT: ${DELVE_DEBUG_PORT}
    ports:
      - "${HOST_HTTP_PORT}:${HTTP_PORT}"
      - "${DELVE_DEBUG_PORT}:${DELVE_DEBUG_PORT}"
