FROM golang:1.23.3 AS golang

WORKDIR /usr/src/app

COPY . .

RUN go mod download && \
    go mod tidy && \
    go build -o ./.bin/go-app ./cmd/order/main.go

RUN go build -o ./.bin/goose-custom ./cmd/tools/goose-custom

FROM busybox:1.37.0

ARG BIN_PATH="/usr/src/app/.bin"
ARG APP_PATH="/usr/app"
ARG HTTP_PORT

COPY --from=golang $BIN_PATH/go-app $APP_PATH/
COPY --from=golang $BIN_PATH/goose-custom $APP_PATH/

COPY ./internal/database/migrations $APP_PATH/database/migrations

EXPOSE $HTTP_PORT

CMD ["./go-app"]
