// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/d-alejandro/go-code-examples/internal/app/order/presenter (interfaces: OrderPresenter)
//
// Generated by this command:
//
//	mockgen -package mocks github.com/d-alejandro/go-code-examples/internal/app/order/presenter OrderPresenter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/d-alejandro/go-code-examples/internal/pkg/models"
	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderPresenter is a mock of OrderPresenter interface.
type MockOrderPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockOrderPresenterMockRecorder
	isgomock struct{}
}

// MockOrderPresenterMockRecorder is the mock recorder for MockOrderPresenter.
type MockOrderPresenterMockRecorder struct {
	mock *MockOrderPresenter
}

// NewMockOrderPresenter creates a new mock instance.
func NewMockOrderPresenter(ctrl *gomock.Controller) *MockOrderPresenter {
	mock := &MockOrderPresenter{ctrl: ctrl}
	mock.recorder = &MockOrderPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderPresenter) EXPECT() *MockOrderPresenterMockRecorder {
	return m.recorder
}

// PresentError mocks base method.
func (m *MockOrderPresenter) PresentError(ctx *gin.Context, statusCode int, errors any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PresentError", ctx, statusCode, errors)
}

// PresentError indicates an expected call of PresentError.
func (mr *MockOrderPresenterMockRecorder) PresentError(ctx, statusCode, errors any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentError", reflect.TypeOf((*MockOrderPresenter)(nil).PresentError), ctx, statusCode, errors)
}

// PresentOrder mocks base method.
func (m *MockOrderPresenter) PresentOrder(arg0 *gin.Context, arg1 *models.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PresentOrder", arg0, arg1)
}

// PresentOrder indicates an expected call of PresentOrder.
func (mr *MockOrderPresenterMockRecorder) PresentOrder(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentOrder", reflect.TypeOf((*MockOrderPresenter)(nil).PresentOrder), arg0, arg1)
}

// PresentOrderList mocks base method.
func (m *MockOrderPresenter) PresentOrderList(arg0 *gin.Context, arg1 []*models.Order) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PresentOrderList", arg0, arg1)
}

// PresentOrderList indicates an expected call of PresentOrderList.
func (mr *MockOrderPresenterMockRecorder) PresentOrderList(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresentOrderList", reflect.TypeOf((*MockOrderPresenter)(nil).PresentOrderList), arg0, arg1)
}
