// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/d-alejandro/go-code-examples/internal/pkg/helpers (interfaces: RenderingHelper)
//
// Generated by this command:
//
//	mockgen -package mocks github.com/d-alejandro/go-code-examples/internal/pkg/helpers RenderingHelper
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRenderingHelper is a mock of RenderingHelper interface.
type MockRenderingHelper struct {
	ctrl     *gomock.Controller
	recorder *MockRenderingHelperMockRecorder
	isgomock struct{}
}

// MockRenderingHelperMockRecorder is the mock recorder for MockRenderingHelper.
type MockRenderingHelperMockRecorder struct {
	mock *MockRenderingHelper
}

// NewMockRenderingHelper creates a new mock instance.
func NewMockRenderingHelper(ctrl *gomock.Controller) *MockRenderingHelper {
	mock := &MockRenderingHelper{ctrl: ctrl}
	mock.recorder = &MockRenderingHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRenderingHelper) EXPECT() *MockRenderingHelperMockRecorder {
	return m.recorder
}

// RenderJSON mocks base method.
func (m *MockRenderingHelper) RenderJSON(ctx *gin.Context, code int, obj any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RenderJSON", ctx, code, obj)
}

// RenderJSON indicates an expected call of RenderJSON.
func (mr *MockRenderingHelperMockRecorder) RenderJSON(ctx, code, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderJSON", reflect.TypeOf((*MockRenderingHelper)(nil).RenderJSON), ctx, code, obj)
}
