// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/d-alejandro/go-code-examples/internal/pkg/helpers (interfaces: ValidationHelper)
//
// Generated by this command:
//
//	mockgen -package mocks github.com/d-alejandro/go-code-examples/internal/pkg/helpers ValidationHelper
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockValidationHelper is a mock of ValidationHelper interface.
type MockValidationHelper struct {
	ctrl     *gomock.Controller
	recorder *MockValidationHelperMockRecorder
	isgomock struct{}
}

// MockValidationHelperMockRecorder is the mock recorder for MockValidationHelper.
type MockValidationHelperMockRecorder struct {
	mock *MockValidationHelper
}

// NewMockValidationHelper creates a new mock instance.
func NewMockValidationHelper(ctrl *gomock.Controller) *MockValidationHelper {
	mock := &MockValidationHelper{ctrl: ctrl}
	mock.recorder = &MockValidationHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidationHelper) EXPECT() *MockValidationHelperMockRecorder {
	return m.recorder
}

// ValidateForm mocks base method.
func (m *MockValidationHelper) ValidateForm(ctx *gin.Context, request any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateForm", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateForm indicates an expected call of ValidateForm.
func (mr *MockValidationHelperMockRecorder) ValidateForm(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateForm", reflect.TypeOf((*MockValidationHelper)(nil).ValidateForm), ctx, request)
}

// ValidateQuery mocks base method.
func (m *MockValidationHelper) ValidateQuery(ctx *gin.Context, request any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateQuery", ctx, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateQuery indicates an expected call of ValidateQuery.
func (mr *MockValidationHelperMockRecorder) ValidateQuery(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateQuery", reflect.TypeOf((*MockValidationHelper)(nil).ValidateQuery), ctx, request)
}
